### ISSUE TITLE
Item.value shall be Vec<ItemValue>

### ISSUE THREAD

**Issue by lucat1** [rossnomann/rust-ape#7]
As stated both on the [specification](https://wiki.hydrogenaud.io/index.php?title=APE_key) as well as on [wikipedia](https://en.wikipedia.org/wiki/APE_tag#Features) the `value` of a `(key, value)` is indeed a "list of values for each key rather than one value per key". Is it possible to access the value of an `ape::Item` as a `Vec<ItemValue>`?

**Comment by rossnomann** [comment]
A proper fix was released just now. Sorry for inconvenience.
